.PHONY: dev build preview install

# Installer les dépendances
install:
	npm install

# Lancer le serveur de développement
dev:
	npm run dev

# Build la documentation
build:
	npm run build

# Preview la build
preview:
	npm run preview

